version: "3"
services:
  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/etc/php.ini
  # apacheを使う場合は下記設定を利用
  #httpd:
  #  build:
  #    context: ./docker/httpd
  #  ports:
  #    - ${HTTPD_PORT}:80
  #  privileged: true
  #  links:
  #    - php
  #  volumes:
  #    - "./src/:/var/www/html"
  #    - "./docker/httpd/apache.conf:/etc/httpd/conf/httpd.conf"

  # nginx を使う場合は下記設定を利用
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - ${HTTPD_PORT}:80
    privileged: true
    volumes:
      - "./src:/var/www/html"
      - "./docker/nginx/default.conf:/etc/nginx/nginx.conf"
    depends_on:
      - php
  mysql:
    build: ./docker/mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./logs:/var/log/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - ${MYSQL_PORT}:3306
volumes:
  dbdata:
