version: "3"
services:
  app:
    build:
      context: ./docker/httpd
    ports:
      - ${HTTPD_PORT}:80
    privileged: true
    volumes:
      - "./src/:/var/www/html"
      - "./docker/httpd/apache.conf:/etc/httpd/conf/httpd.conf"
      - "./docker/httpd/php.ini:/etc/php.ini"
  # 最終的には nginx でも httpd でも動くような作りにしたい
  #web:
  #  image: nginx:alpine
  #  depends_on:
  #    - app
  #  ports:
  #    - ${NGINX_PORT}:80
  #  volumes:
  #    - ${PROJECT_PATH}:/work
  #    - ./logs:/var/log/nginx
  #    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #app:
  #  build: ./docker/php
  #  ports:
  #    - ${LARAVEL_SERVER_PORT}:8000
  #  volumes:
  #    - ${PROJECT_PATH}:/work
  #    - ./docker/ash:/etc/profile.d
  #    - ./logs:/var/log/php
  #  working_dir: /work
  #composer:
  #  build: ./docker/composer
  #  volumes:
  #    - ${PROJECT_PATH}:/work
  #  working_dir: /work  
  mysql:
    build: ./docker/mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./logs:/var/log/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - ${MYSQL_PORT}:3306
volumes:
  dbdata:
